swagger: "2.0"
info:
  title: "Airport Codes"
  description: "Get the name of an airport from its three-letter IATA code."
  version: "1.0.0"
host: "airports-project.appspot.com"
basePath: "/api/v1"
schemes:
  - "https"
paths: 
  /airportName/{iataCode}:
      parameters:
      - name: iataCode
        in: path
        required: true
        description: 'IATA code of the airport'
        type: string
        minLength: 3
        maxLength: 3
      get:
        description: "Get the airport name for a given IATA code."
        operationId: "airportGet"
        responses:
          200:
            description: "Success."
            schema:
              type: object
              properties:
                name:
                  type: string
          400:
            description: "Invalid or missing IATA."
      post:
        description: "Insert the name and the corrispondent IATA code."
        operationId: "airportPost"
        consumes:
          - application/json
        parameters:
          - in: body
            name: airportName
            description: "Name of the airport"
            schema:
              type: string
              maxLength: 250
            required: true
        responses:
          200:
            description: "Success"
          201:
            description: "Conflict with other equal IATA code "
          400:
            description: "Missing IATA code"